//! Turn a directory of rule files into a registry.
//!
//! A lint rule is one file under `src/lint/rules/`. Nothing lists those files
//! by hand, because a hand-written list is one file every rule author must
//! edit, and two authors editing it collide. This script reads the directory
//! and writes the module declarations and the registry into `OUT_DIR`.
//!
//! The same generator runs twice. It runs over the crate's own rules, and over
//! the specimen rules the seam test uses, so the test measures the mechanism
//! that ships rather than a copy of it.

use std::error::Error;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// One directory of rule files, and what the registry built from it is called.
struct Registry {
    /// Where the rule files are, relative to the package root.
    source: &'static str,
    /// The generated file's name inside `OUT_DIR`.
    output: &'static str,
    /// How the generated code names the rule trait.
    trait_path: &'static str,
}

/// The registries this script writes.
const REGISTRIES: &[Registry] = &[
    Registry {
        source: "src/lint/rules",
        output: "lint_rules.rs",
        trait_path: "crate::lint::rule::Rule",
    },
    Registry {
        source: "tests/specimen_rules",
        output: "specimen_rules.rs",
        trait_path: "kicli::lint::Rule",
    },
];

fn main() -> Result<(), Box<dyn Error>> {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);

    println!("cargo:rerun-if-changed=build.rs");
    // The parent of each rule directory is watched as well as the directory
    // itself. A rule directory that does not exist yet has no mtime to watch,
    // and the first rule file added creates it.
    println!("cargo:rerun-if-changed=src/lint");
    println!("cargo:rerun-if-changed=tests");

    for registry in REGISTRIES {
        let source = manifest.join(registry.source);
        println!("cargo:rerun-if-changed={}", registry.source);
        let names = rule_files(&source)?;
        let generated = registry_text(&source, &names, registry.trait_path);
        std::fs::write(out_dir.join(registry.output), generated)?;
    }

    Ok(())
}

/// The module names of every rule file in a directory, in name order.
///
/// A directory that is not there yet holds no rules. That is the state the
/// crate ships in before the first rule is written, and it is not an error.
fn rule_files(dir: &Path) -> Result<Vec<String>, Box<dyn Error>> {
    if !dir.is_dir() {
        return Ok(Vec::new());
    }
    let mut names = Vec::new();
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().is_none_or(|end| end != "rs") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .ok_or_else(|| format!("{} has no readable name", path.display()))?;
        if stem == "mod" {
            return Err(format!(
                "{} names the module list, which is generated",
                path.display()
            )
            .into());
        }
        if !is_module_name(stem) {
            return Err(format!("{} is not a module name", path.display()).into());
        }
        names.push(stem.to_owned());
    }
    // The order is the file name's, not the directory's. A directory hands its
    // entries back in whatever order the file system holds them, and the
    // registry must be the same on every machine.
    names.sort();
    Ok(names)
}

/// Is this a name a `mod` declaration may use?
fn is_module_name(name: &str) -> bool {
    !name.is_empty()
        && !name.starts_with(|first: char| first.is_ascii_digit())
        && name
            .chars()
            .all(|letter| letter.is_ascii_lowercase() || letter.is_ascii_digit() || letter == '_')
}

/// The registry, as Rust source.
fn registry_text(dir: &Path, names: &[String], trait_path: &str) -> String {
    let mut out = String::new();
    out.push_str("// Generated by build.rs. Edits here are lost on the next build.\n\n");

    for name in names {
        let path = dir.join(format!("{name}.rs"));
        let _ = writeln!(out, "#[path = {:?}]", path.display().to_string());
        let _ = writeln!(out, "mod {name};");
    }
    out.push('\n');

    out.push_str("/// Every rule, grouped by the file that declares it, in file-name order.\n");
    let _ = writeln!(
        out,
        "pub static BY_FILE: &[(&str, &[&'static dyn {trait_path}])] = &["
    );
    for name in names {
        let _ = writeln!(out, "    ({name:?}, {name}::RULES),");
    }
    out.push_str("];\n\n");

    out.push_str("/// Every rule this registry holds, in file-name then declaration order.\n");
    out.push_str("#[must_use]\n");
    let _ = writeln!(out, "pub fn all() -> Vec<&'static dyn {trait_path}> {{");
    out.push_str("    BY_FILE\n");
    out.push_str("        .iter()\n");
    out.push_str("        .flat_map(|(_, rules)| rules.iter().copied())\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n\n");

    out.push_str("/// The files this registry was built from, in name order.\n");
    out.push_str("#[must_use]\n");
    out.push_str("pub fn files() -> Vec<&'static str> {\n");
    out.push_str("    BY_FILE.iter().map(|(name, _)| *name).collect()\n");
    out.push_str("}\n");

    out
}
